### ISSUE TITLE
Kalender

### ISSUE THREAD

**Issue by dk1553** [inFumumVerti/DHBWorld#13]
Mit diesem Link kann der Kalender nicht geladen werden:
https://rapla.dhbw-karlsruhe.de/rapla?page=calendar&user=ahrensb&file=TEL20AT&day=1&month=9&year=2022&next=%3E%3E

(Auch wenn man den Tag, Monat und Jahr aus dem Link wegstreicht)

**Comment by blitzdose** [comment]
Fixed with 1.6
