### ISSUE TITLE
Neues Rapla-Format

### ISSUE THREAD

**Issue by dk1553** [inFumumVerti/DHBWorld#24]
Dieser Kalender wird in der App nicht unterstützt:

https://rapla.dhbw.de/rapla/calendar?key=2a9Bq7PTVcTMvCSNwYoQRrO0GK9bccz-i39YnTK__wfzLf7zoDljz6ez6o-rF2Fsp4Cjn3VUMgfKBZ_BsAJvOcGkFsW49XkYpq5u9TSYXj8&salt=11988947&allocatable_id=rd9161f4-18b9-4ec2-8d51-5d9c645c52f0

**Comment by dk1553** [comment]
Es sollte nachgeprüft werden, ob es den gleichen Kalender im Standard-Format gibt?

**Comment by inFumumVerti** [comment]
Dieses Format ist bei dem verwendetem Parser nicht vorgesehen. Ich prüfe, ob ich den Parser hierfür modifizieren kann.
