### ISSUE TITLE
Kalendar springt in die möchte nächste Woche, obwohl es am Samstag eine Vorlesung gibt

### ISSUE THREAD

**Issue by MKrabs** [inFumumVerti/DHBWorld#25]
Wenn man samstags eine Vorlesung hat, und auch "Show Saturdays" eingeschaltet ist, springt der Kalender trotzdem in die nächste Woche hin. 

https://user-images.githubusercontent.com/71791731/205429635-c598d953-019a-4776-84de-9331d8393df6.mp4

**Comment by inFumumVerti** [comment]
Alles klar, ich kümmere mich drum.
