### ISSUE TITLE
Backup  #e8F7sQcUoJbfI8dxKgQHHYhqOt43

### ISSUE THREAD

**Issue by DHBWorld** [inFumumVerti/DHBWorld#57]
Die App hat ein Backup mit dem Namen "Backup (1).dhbworld" gespeichert. Die Wiederstellung von diesem Backup funktioniert nicht: Die Datei wird als Backup-Datei nicht akzeptiert.
(Daria)

Android Version: 11
Manufacturer: Xiaomi
Brand: xiaomi
Model: Redmi Note 8T
Device: willow

Type: bug

**Comment by blitzdose** [comment]
Ich kann den Fehler bei mir nicht reproduzieren. Kannst du bei dir einmal dafür sorgen das der Fehler auftritt und dann in den Einstellungen über "Export Debugging-Log" die logfile speichern und mir zukommen lassen? (Oder auch einfach das Log über Logcat in Android Studio)

**Comment by blitzdose** [comment]
Problem gelöst: Fehlerhafte Backup-Datei
