### ISSUE TITLE
App crashes after login into Dualis

### ISSUE THREAD

**Issue by RobinsCodeOnGit** [inFumumVerti/DHBWorld#9]
# Steps to reproduce
* App öffnen
* In dualis Tab wechseln
* Einloggen
* Biometrie und Login Daten speichern
* Klick auf Login button

# result
* Kurz wird die dualis Ansicht mit den drei Tabs (Übersicht, Kurse, Dokumente) ohne Inhalt gezeigt (unter 1 Sekunde)
* dann schließt sich die App
* Exportiertes Debugging log aus den Einstellungen ist leer

# expected result
* Dualis Noten werden angezeigt 

# additional information
* App version 1.5 from Google play store 
* android version 11
* Allerdings funktioniert DHBW Dualis Notifier an meinem Handy

**Comment by blitzdose** [comment]
Wir haben eine neue Version der App veröffentlicht, welche das Problem mit dem leeren Debugging.log behebt. Bitte versuche dich erneut bei Dualis einzuloggen und das Debugging-log erneut zu exportieren. Beachte aber, dass es momentan anscheinend ein Problem mit Dualis selbst gibt, wodurch Anmeldungen nicht möglich sind.

**Comment by RobinsCodeOnGit** [comment]
Vielen dank, sobald der Login bei dualis wieder möglich ist, erweitere ich das Ticket sofern vonnöten

**Comment by RobinsCodeOnGit** [comment]
Die neuen Logs (sind so abgeschnitten 

`
ime: Process: com.main.dhbworld, PID: 10068
07-08 12:05:15.575 10068 10068 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
07-08 12:05:15.575 10068 10068 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
07-08 12:05:15.575 10068 10068 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisParser.parseDocuments(DualisParser.java:42)
07-08 12:05:15.575 10068 10068 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisAPI.lambda$makeDocumentsRequest$0$com-main-dhbworld-Dualis-DualisAPI(DualisAPI.java:76)
07-08 12:05:15.575 10068 10068 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisAPI$$ExternalSyntheticLambda5.onResponse(Unknown Source:4)
07-08 12:05:15.575 10068 10068 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
07-08 12:05:15.575 10068 10068 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
07-08 12:05:15.575 10068 10068 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
07-08 12:05:15.575 10068 10068 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-08 12:05:15.575 10068 10068 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-08 12:05:15.575 10068 10068 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
07-08 12:05:15.575 10068 10068 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7861)
07-08 12:05:15.575 10068 10068 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 12:05:15.575 10068 10068 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
07-08 12:05:15.575 10068 10068 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
07-08 13:15:29.670 24638 24638 E AndroidRuntime: FATAL EXCEPTION: main
07-08 13:15:29.670 24638 24638 E AndroidRuntime: Process: com.main.dhbworld, PID: 24638
07-08 13:15:29.670 24638 24638 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
07-08 13:15:29.670 24638 24638 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
07-08 13:15:29.670 24638 24638 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisParser.parseDocuments(DualisParser.java:42)
07-08 13:15:29.670 24638 24638 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisAPI.lambda$makeDocumentsRequest$0$com-main-dhbworld-Dualis-DualisAPI(DualisAPI.java:76)
07-08 13:15:29.670 24638 24638 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisAPI$$ExternalSyntheticLambda5.onResponse(Unknown Source:4)
07-08 13:15:29.670 24638 24638 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
07-08 13:15:29.670 24638 24638 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
07-08 13:15:29.670 24638 24638 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
07-08 13:15:29.670 24638 24638 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-08 13:15:29.670 24638 24638 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-08 13:15:29.670 24638 24638 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
07-08 13:15:29.670 24638 24638 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7861)
07-08 13:15:29.670 24638 24638 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 13:15:29.670 24638 24638 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
07-08 13:15:29.670 24638 24638 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
07-08 13:15:52.189 24814 24814 E AndroidRuntime: FATAL EXCEPTION: main
07-08 13:15:52.189 24814 24814 E AndroidRuntime: Process: com.main.dhbworld, PID: 24814
07-08 13:15:52.189 24814 24814 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
07-08 13:15:52.189 24814 24814 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
07-08 13:15:52.189 24814 24814 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisParser.parseDocuments(DualisParser.java:42)
07-08 13:15:52.189 24814 24814 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisAPI.lambda$makeDocumentsRequest$0$com-main-dhbworld-Dualis-DualisAPI(DualisAPI.java:76)
07-08 13:15:52.189 24814 24814 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisAPI$$ExternalSyntheticLambda5.onResponse(Unknown Source:4)
07-08 13:15:52.189 24814 24814 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
07-08 13:15:52.189 24814 24814 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
07-08 13:15:52.189 24814 24814 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
07-08 13:15:52.189 24814 24814 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-08 13:15:52.189 24814 24814 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-08 13:15:52.189 24814 24814 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
07-08 13:15:52.189 24814 24814 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7861)
07-08 13:15:52.189 24814 24814 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 13:15:52.189 24814 24814 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
07-08 13:15:52.189 24814 24814 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
07-08 13:16:00.801 25071 25071 E AndroidRuntime: FATAL EXCEPTION: main
07-08 13:16:00.801 25071 25071 E AndroidRuntime: Process: com.main.dhbworld, PID: 25071
07-08 13:16:00.801 25071 25071 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
07-08 13:16:00.801 25071 25071 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
07-08 13:16:00.801 25071 25071 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisParser.parseDocuments(DualisParser.java:42)
07-08 13:16:00.801 25071 25071 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisAPI.lambda$makeDocumentsRequest$0$com-main-dhbworld-Dualis-DualisAPI(DualisAPI.java:76)
07-08 13:16:00.801 25071 25071 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisAPI$$ExternalSyntheticLambda5.onResponse(Unknown Source:4)
07-08 13:16:00.801 25071 25071 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
07-08 13:16:00.801 25071 25071 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
07-08 13:16:00.801 25071 25071 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
07-08 13:16:00.801 25071 25071 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-08 13:16:00.801 25071 25071 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-08 13:16:00.801 25071 25071 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
07-08 13:16:00.801 25071 25071 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7861)
07-08 13:16:00.801 25071 25071 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 13:16:00.801 25071 25071 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
07-08 13:16:00.801 25071 25071 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
07-08 13:16:07.421 25180 25180 E AndroidRuntime: FATAL EXCEPTION: main
07-08 13:16:07.421 25180 25180 E AndroidRuntime: Process: com.main.dhbworld, PID: 25180
07-08 13:16:07.421 25180 25180 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
07-08 13:16:07.421 25180 25180 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
07-08 13:16:07.421 25180 25180 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisParser.parseDocuments(DualisParser.java:42)
07-08 13:16:07.421 25180 25180 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisAPI.lambda$makeDocumentsRequest$0$com-main-dhbworld-Dualis-DualisAPI(DualisAPI.java:76)
07-08 13:16:07.421 25180 25180 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisAPI$$ExternalSyntheticLambda5.onResponse(Unknown Source:4)
07-08 13:16:07.421 25180 25180 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
07-08 13:16:07.421 25180 25180 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
07-08 13:16:07.421 25180 25180 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
07-08 13:16:07.421 25180 25180 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-08 13:16:07.421 25180 25180 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-08 13:16:07.421 25180 25180 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
07-08 13:16:07.421 25180 25180 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7861)
07-08 13:16:07.421 25180 25180 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 13:16:07.421 25180 25180 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
07-08 13:16:07.421 25180 25180 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
07-08 13:16:24.880 25301 25301 E AndroidRuntime: FATAL EXCEPTION: main
07-08 13:16:24.880 25301 25301 E AndroidRuntime: Process: com.main.dhbworld, PID: 25301
07-08 13:16:24.880 25301 25301 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
07-08 13:16:24.880 25301 25301 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
07-08 13:16:24.880 25301 25301 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisParser.parseDocuments(DualisParser.java:42)
07-08 13:16:24.880 25301 25301 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisAPI.lambda$makeDocumentsRequest$0$com-main-dhbworld-Dualis-DualisAPI(DualisAPI.java:76)
07-08 13:16:24.880 25301 25301 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisAPI$$ExternalSyntheticLambda5.onResponse(Unknown Source:4)
07-08 13:16:24.880 25301 25301 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
07-08 13:16:24.880 25301 25301 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
07-08 13:16:24.880 25301 25301 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
07-08 13:16:24.880 25301 25301 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-08 13:16:24.880 25301 25301 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-08 13:16:24.880 25301 25301 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
07-08 13:16:24.880 25301 25301 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7861)
07-08 13:16:24.880 25301 25301 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 13:16:24.880 25301 25301 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
07-08 13:16:24.880 25301 25301 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
07-08 13:18:21.354 25433 25433 E AndroidRuntime: FATAL EXCEPTION: main
07-08 13:18:21.354 25433 25433 E AndroidRuntime: Process: com.main.dhbworld, PID: 25433
07-08 13:18:21.354 25433 25433 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
07-08 13:18:21.354 25433 25433 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
07-08 13:18:21.354 25433 25433 E AndroidRuntime: 	at com.main.dhbworld.Dualis.DualisParser.parseDocuments(DualisParser.java:42)
07-08 13:18:21.354 25433 25433 E AndroidRuntime: 	at 
`

Version: 1.2
STR und Result gleich aber mit funktionierenden Logs

**Comment by blitzdose** [comment]
Fixed with new Version. Available as GitHub-Release or from the Google PlayStore in a few hours
